#cloud-config
disable_root: true
timezone: Moscow
repo_update: true
repo_upgrade: true
apt:
  preserve_sources_list: true

packages:
##  - epel-release
 - nginx
##
runcmd:
  - [ systemctl, enable, nginx.service ]
  - [ systemctl, start, --no-block, nginx.service ]
  - [ chown, -R, "ansible:www-data", /var/www/html ]
  - [ sh, -c, "echo '<html><h1>Application Load Balancer\n</h1></html>' > /var/www/html/index.html"]
  - [ sh, -c, "echo $(hostname | cut -d '.' -f 1 ) >> /var/www/html/index.html" ]


users:
 - name: ansible
   groups: sudo
   shell: /bin/bash
   sudo: ['ALL=(ALL) NOPASSWD:ALL']
   ssh-authorized-keys:
     - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKtRGiRY8xgoaoRgFAP2zbn73GfBX7xkGZSTaLodiJDk andr-mozha@yandex.ru
