all:
  children:

    jump:
      hosts:
        bastion:
          ansible_host: 51.250.98.32
      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        ansible_host_key_checking: false

    webservers:
      hosts:
        webserver-1:
          ansible_host: 192.168.1.22
        webserver-2:
          ansible_host: 192.168.2.12
        webserver-3:
          ansible_host: 192.168.2.18

    observability:
      hosts:
        prometheus:
          ansible_host: 192.168.4.25
        grafana:
          ansible_host: 192.168.10.35
        elastic:
          ansible_host: 192.168.4.3
        kibana:
          ansible_host: 192.168.10.34

    prometheus_host:
      hosts:
        prometheus:

  vars:
    ansible_ssh_common_args: '-J ansible@51.250.98.32 -o StrictHostKeyChecking=no'
    ansible_host_key_checking: false
    ansible_user: ansible
    ansible_become: true
    ansible_workdir: /home/ansible/ansible_project